config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :recipes, only: [:show, :new, :create, :edit, :update, :index] do
    get 'search', on: :collection
  end
  resources :cuisines, only: [:show, :new, :create, :edit, :update]
  resources :recipe_types, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes
  validates :name, presence: { message: 'A cozinha deve ter um nome' }
  validates :name, uniqueness: { message: 'Esse nome de cozinha ja existe' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  validates :title, :difficulty, :cook_time,
            :ingredients, :method, presence: true
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :set_cuisine, only: [:show, :edit, :update]
  def show
  end

  def edit
  end

  def update
    if @cuisine.update(cuisine_params)
      redirect_to @cuisine
    else
      render 'edit'
    end

  end
  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to @cuisine
    else
      render 'new'
    end
  end

  private
  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.last(6)
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def show
    @recipe_type = RecipeType.find(params[:id])
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(params.require(:recipe_type).permit(:name))
    if @recipe_type.save
      redirect_to @recipe_type
    else
      flash[:error] = 'Você deve informar o nome do tipo de receita'
      render :new
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def index
    @recipes = Recipe.all
  end

  def new
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      render 'new'
    end
  end

  def edit
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      render 'new'
    end
  end

  def search
    @search_term = params[:search]
    @recipes = Recipe.where(title: @search_term)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id, :difficulty,
                                  :cook_time, :ingredients, :method)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/edit.html.erb
<ul>
<%  @cuisine.errors.full_messages.each do |message|  %>
    <li><%= message%>
<% end %>
</ul>
<%= form_for @cuisine  do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar'  %>
<%end%>

app/views/cuisines/new.html.erb
<h1>Cadastrar Nova Cozinha</h1>
<% if flash[:error] %>
  <%= flash[:error] %>
<% end %>
<%= form_for @cuisine do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>
<%= link_to 'Editar', edit_cuisine_path%>
<% if @cuisine.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>
<% @cuisine.recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-3 col-xs-12">
    <%= render 'shared/aside' %>
  </div>
  <div class="col-md-9 col-xs-12">
    <% @recipes.each do |recipe| %>
      <h1><%= link_to recipe.title, recipe %></h1>
      <ul>
        <li><%= recipe.recipe_type.name %></li>
        <li><%= recipe.cuisine.name %></li>
        <li><%= recipe.difficulty %></li>
        <li><%= recipe.cook_time %> minutos</li>
      </ul>
    <% end %>
  </div>
  <%= link_to 'Ver todas receitas', recipes_path, class: 'btn btn-default' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="container">
      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <h1><%= link_to 'CookBook', root_path %></h1>
            </div>
            <div class="navbar-right">
              <p class="navbar-text">Bem-vindo ao maior livro de receitas online</p>
              <%= render 'shared/search_form' %>
              <%= link_to 'Enviar uma receita', new_recipe_path, class: 'btn btn-success navbar-btn' %>
              <% if user_signed_in?%>
                Olá <%= current_user.email%> <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
              <% else %>
              <%= link_to 'Login', new_user_session_path %>
              <% end %>
            </div>
          </div>
        </nav>
      </header>
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipe_types/new.html.erb
<%= flash[:error] %>

<%= form_for(@recipe_type) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<% if @recipe_type.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de receitas</p>
<% end %>
<% @recipe_type.recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :recipe_type_id, 'Tipo da Receita' %>
    <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select :cuisine_id, @cuisines, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.text_field :cook_time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_area :ingredients , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :method, 'Como Preparar' %>
    <%= f.text_area :method , class: "form-control" %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editar receita</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>Receitas</h1>

<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/recipes/new.html.erb
<h1>Enviar uma receita</h1>
<%= render 'form' %>

app/views/recipes/search.html.erb
<h1>Resultado da busca por: <%= @search_term %></h1>

<% @recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>
<p><%= @recipe.recipe_type.name %></p>
<p><%= @recipe.cuisine.name %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time %> minutos</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.method %></p>

<%= link_to 'Editar', edit_recipe_path(@recipe), class: 'btn btn-primary' %>
<%= link_to 'Voltar', root_path, class: 'btn btn-default' %>

app/views/shared/_aside.html.erb
<aside>
  <h2>Cozinhas</h2>
  <ul>
    <% @cuisines.each do |cuisine| %>
      <li><%= link_to cuisine.name, cuisine %></li>
    <% end %>
  </ul>

  <h2>Tipos</h2>
  <ul>
    <% @recipe_types.each do |type| %>
      <li><%= link_to type.name, type %></li>
    <% end %>
  </ul>
</aside>

app/views/shared/_search_form.html.erb
<%= form_tag(search_recipes_path, method: :get, class: 'navbar-form navbar-left') do %>
  <div class="form-group">
  <%= label_tag :search, 'Busca' %>
  <%= text_field_tag :search, nil, class: 'form-control' %>
  </div>
  <%= submit_tag 'Buscar', class: 'btn btn-primary'  %>
<% end %>